---
apiVersion: v1
kind: Service
metadata:
  name: emojify-cache-service
spec:
  selector:
    app: emojify-cache
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emojify-cache
  labels:
    app: emojify-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emojify-cache
  template:
    metadata:
      labels:
        app: emojify-cache
    spec:
      containers:
      - name: emojify-cache
        image: "nicholasjackson/emojify-cache:v0.3.9"
        ports:
        - containerPort: 9090
        - name: BIND_ADDRESS
          value: "0.0.0.0"
