---
apiVersion: v1
kind: Service
metadata:
  name: emojify-facebox-service
spec:
  selector:
    app: emojify-facebox
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8003

---                                                    
apiVersion: apps/v1                                    
kind: Deployment
metadata:
  name: emojify-facebox
  labels:
    app: emojify-facebox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emojify-facebox
  template:
    metadata:
      labels:
        app: emojify-facebox
    spec:
      containers:
      - name: emojify-facebox
        image: "machinebox/facebox"
        env:
        - name: MB_KEY
          valueFrom:
            secretKeyRef:
              name: emojify
              key: mb_key
        - name: MB_ADDRESS
          value: "127.0.0.1"
        - name: MB_PORT
          value: "8080"